name: Makefile CI

on:
  push:
    branches: [ "python-kin-refactor" ]
  pull_request:
    branches: [ "python-kin-refactor" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run testing workflow
      run: make test
